#FACA UM PROGRAMA QUE MOSTRE NA TELA UMA CONTAGEM REGRESSIVA PARA O ESTOURO DE FOGOS DE ARTIFICIO, INDO DE 10 ATE 0, COM UMA PAUSA DE 1 SEGUNDO ENTRE ELES.

from time import sleep
for c in range(10, 0, -1):
    print(c)
    sleep(1)    
print('HAPPY NEW YEAR !!!')
