#CRIE UM PROGRAMA QUE LEIA VARIOS NUMEROS INTEIROS PELO TECLADO.
#O PROGRAMA SO VAI PARAR QUANDO O USUARIO DIGITAR O VALOR 999, QUE E A CONDICAO DE PARADA.
#NO FINAL, MOSTRE QUANTOS NUMEROS FORAM DIGITADOS E QUAL FOI A SOMA ENTRE ELES.

n = 0
while n != 999:
    n = int(input('Digite um numero: '))
print('FIM')
    