#REFACA O DESAFIO 35 DOS TRIANGULOS, ACRESCENTANDO O RECURSO DE MOSTRAR QUE TIPO DE TRIANGULO SERA FORMADO:
#EQUILATERO - TODOS OS LADOS IGUAIS
#ISOCELES - DOIS LADOS IGUAIS
#ESCALENO - TODOS OS LADOS DIFERENTES

#DESAFIO 35 - DESENVOLVA UM PROGRAMA QUE LEIA O COMPRIMENTO DE 3 RETAS E DIGA AO USUARIO SE ELAS PODEM OU NAO FORMAR UM TRIANGULO.

s1 = float(input('Primeiro segmento: '))
s2 = float(input('Segundo segmento: '))
s3 = float(input('Terceiro segmento: '))

if s1 == s2 and s1 == s3 and s2 == s3:
    print('TRIANGULO EQUILATERO')
elif s1 == s2  or s1 == s3 or s2 == s3:
    print('TRIANGULO ISOCELES')
else:
    print('TRIANGULO ESCALENO')
