#CRIE UM PROGRAMA QUE LEIA QUANTO DINEHRIO VC TEM NA CARTEIRA E MOSTRE QUANTOS DÓLARES VC PODE COMPRAR (DÓLAR=3,27)

m = float(input ('HOW MANY CASH YOU HAVE? R$'))

print ('YOU HAVE {} AND YOU CAN BUY ${:.2f}' .format (m, m/3.27))

